### ISSUE TITLE
Special node: `concat`

### ISSUE THREAD

**Issue by sneakers-the-rat** [miniscope/noob#12]
Like `Return`, we need a special node type that takes a bunch of positional dependencies and concats them into a list.

This is necessary because the syntax

```yaml
depends:
- a.val1
- b.val2
```

would pass each of those as separate positional arguments.  Some functions like `sum` expect an iterable of arguments like

```python
sum([1,2,3])
```

and we might want to use a builtin like `sum` like this

```yaml
b1:
  type: sum # should be possible to just use builtins
  depends:
  - a.val1
  - b.val2
```

so instead we need some way of doing this

```yaml

b0:
  type: concat
  depends:
  - a.val1
  - b.val2
b1:
  type: sum
  depends:
    - b0.value
```

this is sort of awkward to need to do every time, so this is a tentative idea. we may instead want to have an additional keyword that says "treat these positional arguments as a list" or a way of doing generic structuring/destructuring operations like

```yaml
b1:
  type: sum
  depends:
    - - a.val1
      - b.val2 
```

**Comment by raymondwjang** [comment]
i support lessening the number of nodes in this case - feels like we would want to "replicate" the function parameter space as much as possible in 'depends'. also it feels like the second option is something people would instinctively try. 

i'm not the biggest fan of how nested hyphens look but i think the following is equivalent?:
 
```yaml
b1:
  type: sum
  depends:
    - [a.val1, b.val2]
```
