### ISSUE TITLE
Convert test cases to node-only mode

### ISSUE THREAD

**Issue by sneakers-the-rat** [miniscope/noob#19]
Currently we have some special logic in the edges to handle cases of cardinality expansion and contraction: `gather` and `map`

these translate into an "elaborated" or parameterized dependency specification like this:

```yaml
nodes:
  a1:
    type: noob.testing.count_source
  a2:
    type: noob.testing.sporadic_word
  b:
    type: noob.testing.dictify
    depends:
    - items:
        source: a1.index
        edge:
          type: gather
          trigger: a_key
    - a_key: a2.word
  c:
    type: return
    depends:
    - word: b.value
```

this is undesirable because it complicates the runner logic - 
we no longer have a clean topo sorting between nodes, and we effectively have a bipartite graph between nodes and parameterized edges.

We should instead just have these special cases as `gather` and `map` nodes

```yaml
nodes:
  a1:
    type: noob.testing.count_source
  a2:
    type: noob.testing.sporadic_word
  b:
    type: gather
    depends:
      - value: a1.index
      - trigger: a2.word
  c:
    type: noob.testing.dictify
    depends:
    - items: b.index
    - a_key: a2.word
  d:
    type: return
    depends:
    - word: c.value
```
