### ISSUE TITLE
'value' Default for Nameless Output Events

### ISSUE THREAD

**Issue by raymondwjang** [miniscope/noob#22]
Currently, the output events from nodes are tagged via the annotated type with `Name` class.
An event is called by a node in a given format:

```python
def word_source() -> Generator[A[str, Name("word")]]:
    fake = Faker()
    while True:
        yield fake.unique.word()

def exclaim(string: str) -> str:
    return string + "!"
```

```yaml
a:
  type: noob.testing.word_source

b:
  type: noob.testing.exclaim
  depend:
    string: a.word
```

we need to set up the default case for when the type annotation does not exist, so that instead of `a.word`, we can specify `a.value` as a general catch-all.

```python
def word_source() -> Generator:
    fake = Faker()
    while True:
        yield fake.unique.word()

def exclaim(string: str) -> str:
    return string + "!"
```

```yaml
a:
  type: noob.testing.word_source

b:
  type: noob.testing.exclaim
  depend:
    string: a.value
```
